name: Deploy Angular to GitHub Pages

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  # Set this to your repo name for project sites (e.g., plantesitter)
  REPO_NAME: REPO_NAME_HERE

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install deps (use ci if lockfile exists; otherwise install)
      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          elif [ -f pnpm-lock.yaml ]; then
            corepack enable
            pnpm install --frozen-lockfile=false
          elif [ -f yarn.lock ]; then
            corepack enable
            yarn install --frozen-lockfile=false
          else
            npm install
          fi

      # Build (use defaultProject from angular.json; set base-href for project site)
      - name: Build Angular
        run: |
          DEFAULT_PROJECT=$(node -p "require('./angular.json').defaultProject")
          echo "Default project: $DEFAULT_PROJECT"
          npm run build -- --configuration production --base-href "/$REPO_NAME/"

      # Copy index.html -> 404.html for SPA routing
      - name: Prepare 404 fallback
        run: |
          OUT="dist/$(node -p "require('./angular.json').defaultProject")/browser"
          cp "$OUT/index.html" "$OUT/404.html"

      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist/$(node -p "require('./angular.json').defaultProject")/browser

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deploy
