name: Deploy Angular to GitHub Pages

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  # Set this to your repo name for project sites (e.g., plantesitter)
  REPO_NAME: plantesitter

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install deps (use ci if lockfile exists; otherwise install)
      - name: Install dependencies
        working-directory: application/web
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          elif [ -f pnpm-lock.yaml ]; then
            corepack enable
            pnpm install --frozen-lockfile=false
          elif [ -f yarn.lock ]; then
            corepack enable
            yarn install --frozen-lockfile=false
          else
            npm install
          fi

      # Build Angular application
      - name: Build Angular
        working-directory: application/web
        run: npm run build -- --base-href "/plantesitter/"

      # Copy index.html -> 404.html for SPA routing
      - name: Prepare 404 fallback
        working-directory: application/web
        run: |
          cp "dist/plantesitter/browser/index.html" "dist/plantesitter/browser/404.html"

      - uses: actions/upload-pages-artifact@v3
        with:
          path: application/web/dist/plantesitter/browser

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
